<?php

/**
 * PluginCityMasterTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginCityMasterTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginCityMasterTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginCityMaster');
    }
}