<?php

/**
 * PluginJgdcAddressMaster
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class PluginJgdcAddressMaster extends BaseJgdcAddressMaster
{
  /**
   * Return Prefecture code
   *
   * @return string Prefecture code
   */
  public function getPrefectureCode()
  {
    return substr($this->getNewMaCode(), 0, 2);
  }

  /**
   * Return City code
   *
   * @return string City code
   */
  public function getCityCode()
  {
    return substr($this->getNewMaCode(), 0, 5);
  }

  /**
   * Return Area code
   *
   * @return string Area code
   */
  public function getAreaCode()
  {
    return substr($this->getNewMaCode(), 5, 6);
  }
}
