<?php

/**
 * PluginAreaMasterTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginAreaMasterTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginAreaMasterTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginAreaMaster');
    }
}