<?php

/**
 * PluginPrefectureMasterTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginPrefectureMasterTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginPrefectureMasterTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginPrefectureMaster');
    }
}