<?php

/**
 * PluginJgdcAddressMasterTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginJgdcAddressMasterTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginJgdcAddressMasterTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginJgdcAddressMaster');
    }
}